<?php

/**
 * Copyright 2012, Eugene Poberezkin. All rights reserved.
 * http://WhoYouMeet.com - we help you meet more people you need
 *
 *---------------------------------------------------------------
 * File /WYM_info.php
 *
 * Application development information, comments and the list of files
 *---------------------------------------------------------------
 *
 * This is a version 0.1 of Who You Meet application, it has a very limited functionality
 *
 * Application is developed using CodeIgniter framework version 2.1.3 (=CI)
 *
 *
 * It has configuration files for 4 environments:
 *		'local' - to run on a local MAMP installation
 *		'dev' - development version at http://dev.whoyoumeet.com
 *		'beta' - testing version at http://beta.whoyoumeet.com
 *		'production' - public version at http://whoyoumeet.com
 *
 * Environment is set in /index.php file
 *
 *
 * Web pages are using jquery in a very limited way and are fully based on Twitter
 * bootstrap styles and layouts.
 *
 *
 * Controller name and function in controller are called based on path, no custom routing is used
 * 3rd and 4th element in path are passed as function parameters.
 *
 * So, path /cont/func/action/param will call function func() from Cont class defined in file
 *  /application/controllers/cont.php using parameters with values 'action' and 'param'.
 *
 *
 *
 *---------------------------------------------------------------
 * Setup
 *---------------------------------------------------------------
 *
 * MySQL database should be configured, all tables can be created by /Database setup/empty_setup.sql
 *
 * All CI configuration is already done in files, no additional configuration is needed
 *
 * CI sessions are NOT stored in the database, they are fully stored in a cookie unlike
 * PHP sessions, but they are encrypted. Database storage should be implemented.
 *
 *
 *
 *---------------------------------------------------------------
 * Application functionality implemented
 *---------------------------------------------------------------
 *
 * I. Login/signup
 * -------------------------------------------------
 *		1. Twitter login/signup - uses TwitterOAuth library by Abraham Williams
 *		   wrapped in twconnect.php CI library
 *		2. LinkedIn login/signup - uses Simple-LinkedIn PHP by Paul Mennega
 *		   wrapped in in_connect.php CI library
 *		3. Facebokk login/signup - uses Facebook PHP SDK
 *		   wrapped in fbconnect.php CI library
 *		2. Email login/signup (path: /login, /signup)
 *		3. Password recovery (path: /login/recover)
 *		4. Email verification (path: /signup/verify_email)
 *
 * II. The list of people to meet
 * -------------------------------------------------
 *		1. Display the list of people (not users, just info about people) (path: /i/iMeet)
 *		2. Add person via form (path: /i/iMeet/new)
 *		3. Adding person via popup by specifying any of social profile(s)
 *		4. Editing information about people added, including specifying and
 *		   checking their social profiles (/i/iMeet/edit)
 *		5. Viewing information about the person (/i/iMeet/person)
 *
 * III. The list of poeple who want to meet user
 * -------------------------------------------------
 *		1. Displaying the list (path: /i/meetMe)
 *		   The list is automatically generated by matching any of social profiles
 *		   of current user with the social profiles of people other users want to meet
 *		   (see model /application/models/model_users.php).
 *		2. Viewing user profile (/i/meetMe/user)
 *		   At the moment there is no such thing as public user profile.
 *		   You can only see the profile of a user if he/she wants to meet you
 *
 * IV. User pofile
 * -------------------------------------------------
 *		1. Viewing the profile of the current user (/i/profile)
 *		2. Editing the profile of a current user (/i/profile/edit)
 *
 *
 *
 *---------------------------------------------------------------
 * Application files
 *---------------------------------------------------------------
 *
 * Only files changed or added to CI framework files are listed here.
 *
 *
 *	I.	Webroot
 * -------------------------------------------------
 *
 *		/img - images directory
 *			/logos,
 *			/colored icons - not used in web application
 *
 * 		/css
 *			style.css - additional application styles, used in a limited way
 *				a lot of styling is done inline
 *			bootstrap.css
 *			bootstrap-responsive.css - currently not used, as some layouts became unpredictable
 *
 * 		/js
 *			googleanalytics.js - not really used, the same code is inserted in view_footer.php
 *			social_fields.js - ajax checks whether social profiles exist,
 *				used when adding or editing a person to meet
 *
 * 		/Database setup
 *			empty_setup.sql - creates database with all table structures
 *			sample_setup.sql - creates database with the current data (22/11/2012)
 *
 *
 *	II.	Configuration files (/application/config)
 * -------------------------------------------------
 *		/local,
 *		/dev,
 *		/beta,
 *		/production - versions of some config files, that
 *			are different for different environments (see above).
 *			Only config.php and database.php are different
 *
 *		config.php - base URL and cookie settings
 *		routes.php - defines default controller ('i')
 *		autoload.php - defines libraries and helpers that are auto-loaded
 *		database.php - database settings
 *
 *		twitter.php,
 *		linkedin.php,
 *		facebook.php - Who You Meet app keys
 *
 *
 *	III.Controllers (/application/controllers)
 * -------------------------------------------------
 *		i.php - main controller, most application functionality is here
 *		login.php - email and social login/signup, password recovery
 *		signup.php - email signup and email verification
 *
 *		debug.php - shows session data for debugging
 *
 *		twtest.php - not needed (twconnect.php library test)
 *		intest.php - not needed (in_connect.php library test)
 *
 *
 *	IV.	Helpers (/application/helpers)
 * -------------------------------------------------
 *		MY_url_helper.php - different functions that extend url helper
 *		social_helper.php - social networks profiles functions
 *
 *
 *	V.	Libraries (/application/libraries)
 * -------------------------------------------------
 *		External libraries:
 *		/SLIP - Simple-LinkedIn PHP v 3.2.0 library by Paul Mennega (http://www.linkedin.com/in/paulmennega).
 *			This library can be downloaded here - http://code.google.com/p/simple-linkedinphp/
 *		/twitteroauth - TwitterOAuth library by Abraham Williams
 *		/facebook - Facebook PHP SDK
 *
 *		Application libraries
 *		twconnect.php - Twitter library
 *		in_connect.php - LinkedIn library
 *		fbconnect.php - Facebook library, very very limited
 *
 *
 *	VI.	Models (/application/models)
 * -------------------------------------------------
 *		model_users.php - operations with 'users' table, including the list of users
 *			who want to meet the current user (uses 'peopletomeet' table)
 *		model_imeet.php - operations with 'peopletomeet' table
 *
 *
 *	VI.	Views (/application/views)
 * -------------------------------------------------
 *
 *		/includes - views used in more than one page
 *
 *		1.	Parts of most pages:
 *		---------------------------------------
 *			view_template.php - main template file used to "assemble" all pages
 *			view_header.php - header part of all pages with <body> tag
 *			view_navbar.php - navigation bar (styled by Twitter bootstrap)
 *			view_footer.php - footer part of every page, includes some scripts
 *				and Google analytics code
 *
 *		2.	Additional page elements:
 *		---------------------------------------
 *			view_alerts.php - displays validation errors and messages passed
 *				via flash session data, should be added to every page which is supposed to display it
 *			view_share_buttons.php - social sharing buttons
 *
 *		3.	Content templates:
 *		---------------------------------------
 *			view_person_template.php - used to display information about current user,
 *				user to meet and any person added to the list
 *			view_table_template.php - used to display table part of 'people to meet' page
 *				and 'users that want to meet me' page
 *
 *	4.	Home Page:
 *	---------------------------------------
 *		view_home.php - home page
 *
 *	5.	People who user wants to meet:
 *	---------------------------------------
 * 		view_iMeet.php - List of people user wants to meet, the main part of /i/iMeet webpage
 *		view_iMeet_form.php - Form to edit person's information,
 *			main part of  /i/iMeet/new and /i/iMeet/edit/$person->id webpages
 *		view_person.php - Person to meet info main part of /i/iMeet/person webpage
 *
 *	6.	Users who want to meet current user
 *	---------------------------------------
 *		view_meetMe.php - List of people who want to meet me (current user),
 *			main part of /i/meetMe webpage
 *		view_user.php - Viewing user, who wants to meet current user
 *
 *	7.	Login/signup:
 *	---------------------------------------
 *		view_login.php - Main part of /Login webpage
 *		view_signup.php - New user signup via email
 *		view_profile.php - User profile, main part of /i/profile webpage
 *		view_settings.php - Editing user profile
 *		view_change_password.php - forgotten password recovery
 *
 *	8.	Password recovery:
 *	---------------------------------------
 *		view_recover.php - Password recovery request page (/login/recover)
 *		view_recover_password.php - Password change during recovery, (/login/recover_password)
 *
 *	9.	Debugging:
 *	---------------------------------------
 *		view_debug.php - debug information
 *
 *
 *
 *
 * End of file /WYM_info.php */